client_id = '#{client_id}#'
client_secret = '#{client_secret}#'
subscription_id = '#{subscription_id}#' 
tenant_id       = '#{tenant_id}#' 
datadog_api_key = '#{datadog_api_key}#'
datadog_app_key = '#{datadog_app_key}#' 
